// This directive will create a reference to the Server Function and pass that reference to the
// Client Component. When the function is called on the client, React will send a request to the
// server to execute the function and return the result.
'use server';

// Zod for type validation schema
import { z } from 'zod';
import postgres from 'postgres';
// Allows to invalidate cached data on demand for a specific path. Can be called in Server Functions
// and route handlers.
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { signIn } from '@/auth';
import { AuthError } from 'next-auth'; 


const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

// Server Function that passes a reference to the client for authentication
export async function authenticate(
    prevState: string | undefined,
    formData: FormData,
) {
    try {
        await signIn('credentials', formData);
    } catch (error) {
        if (error instanceof AuthError) {
            switch (error.type) {
                case 'CredentialsSignin':
                    return 'Invalid credentials';
                default:
                    return 'Something went wrong';
            }
        }
        throw error;
    }
}

const FormSchema = z.object({
    id: z.string(),
    customerId: z.string({
        invalid_type_error: 'Please select a customer.',
    }),
    // Coerces the input into the right type -> Number(input)
    amount: z.coerce.number()
        .gt(0, {message: 'Please enter an amount greater than $0'}),
    status: z.enum(['pending', 'paid'], {
        invalid_type_error: 'Please select an invoice status.',
    }),
    date: z.string(),
});

// When the user submits the form for creating a new invoice, we do not have the `id` and the `date`
// fields as they are generated by the by the database operations.
const CreateInvoice = FormSchema.omit({id: true, date: true});
const UpdateInvoice = FormSchema.omit({id: true, date: true});

// Server Actions (now Server Functions) allow Client Components to call async functions executed on
// the server.

export type State = {
    errors?: {
        customerId?: string[];
        amount?: string[];
        status?: string[];
    };
    message?: string | null;
}

export async function createInvoice(previousState: State, formData: FormData) {
    // Extract the form values
    const rawFormData = {
        customerId: formData.get('customerId'),
        amount: formData.get('amount'),
        status: formData.get('status'),
    };

    // Validate the types using zod
    const validateFields = CreateInvoice.safeParse(rawFormData);

    // If form validation fails, return errors early. Otherwise, continue.
    if (!validateFields.success) {
        return {
            errors: validateFields.error.flatten().fieldErrors,
            message: 'MissingFields. Failed to Create Invoice.',
        }
    }

    const {customerId, amount, status} = validateFields.data;
    // It is good practice to store monetary values in cents in your database to eliminate JS
    // floating-point errors and ensure greater accuracy.
    const amountInCents = amount * 100;
    // Create a new `YYYY-MM-DD` date
    const date = new Date().toISOString().split('T')[0];

    try {
        await sql`
            INSERT INTO invoices (customer_id, amount, status, date)
            VALUES (${customerId}, ${amountInCents}, ${status}, ${date})
        `;
    } catch (error: any) {
        return {
            message: 'Database Error: Failed to Create Invoice.',
        }
    }

    // Revalidate the cache for the invoices specific page path, with fresh data fetched from the
    // server
    revalidatePath('/dashboard/invoices');
    // Redirect the user back to the `/dashboard/invoices` page
    redirect('/dashboard/invoices');
}

export async function updateInvoice(id: string, previousState: State, formData: FormData) {
    // Extract the form values
    const rawFormData = {
        customerId: formData.get('customerId'),
        amount: formData.get('amount'),
        status: formData.get('status'),
    };

    // Validate the types using zod
    const validateFields = UpdateInvoice.safeParse(rawFormData);

    console.log(validateFields);

    // If form validation fails, return errors early. Otherwise, continue.
    if (!validateFields.success) {
        console.log("here");
        return {
            errors: validateFields.error.flatten().fieldErrors,
            message: 'Missing Fields. Failed to Update Invoice.',
        }
    }

    const {customerId, amount, status} = validateFields.data;

    // It is good practice to store monetary values in cents in your database to eliminate JS
    // floating-point errors and ensure greater accuracy.
    const amountInCents = amount * 100;

    try {
        await sql`
            UPDATE invoices
            SET customer_id = ${customerId}, amount = ${amountInCents}, status = ${status}
            WHERE id = ${id}
        `;
    } catch (err: any) {
        // Log the error to the console
        console.error(err);
        return err.toString();
    }

    // Revalidate the cache for the invoices specific page path, with fresh data fetched from the
    // server
    revalidatePath('/dashboard/invoices');
    // Redirect the user back to the `/dashboard/invoices` page
    redirect('/dashboard/invoices');
}

// Delete an invoice identified by `id`
export async function deleteInvoice(id: string, previousState: State, formData: FormData) {
    try {
        await sql`DELETE FROM invoices WHERE id = ${id}`;
    } catch (err: any) {
        // Log the error to the console
        console.error(err);
        return err.toString();
    }

    revalidatePath('/dashboard/invoices');
    // Redirect the user back to the `/dashboard/invoices` page
    redirect('/dashboard/invoices');
}